### ISSUE TITLE
Every time I press a key, I want to search right away.

### ISSUE THREAD

**Issue by souljungkim** [JinseobBae/spread-sheet-project#14]
It's best to use a supported API.

But if it doesn't support it, I think you can use a trick like below.

## Test

I tested that inserting this script into the '`oninput`' attribute of the '`all search column elements`' at the top of the table makes it `searchable by keystroke every time`.

so... 

result was..

It works! :D

1. `script` to `trick` using oninput attribute
    ```js
    var el=event.target, e=document.createEvent('HTMLEvents'); 
    e.initEvent('keydown', false, true); 
    e.which = 13; 
    e.keyCode = 13; 
    el.dispatchEvent(e);
    window.getSelection().collapseToEnd();
    ```

2. applied to the oninput attribute of element
    ```html
    <td 
        data-v-3a47cd86="" data-v-3b2e3af7="" id="uid28" contenteditable="true" ondragenter="event.preventDefault(); event.dataTransfer.dropEffect = 'none'" 
        ondragover="event.preventDefault(); event.dataTransfer.dropEffect = 'none'" autocomplete="off" autocorrect="off" autocapitalize="off" 
        spellcheck="false" tabindex="-1" class="cell column-filter" colspan="1" style="top: 29px; cursor: text;" 

        oninput="var el=event.target, e=document.createEvent('HTMLEvents'); e.initEvent('keydown', false, true); e.which = 13; e.keyCode=13; el.dispatchEvent(e); window.getSelection().collapseToEnd();"
    >
    typed words by user
    </td>
    ```

3. then, Every time I typed a key, it was immediately searched.

## Plan

It seems to be possible to handle event like '`load`' by applying the event or property to the search column element.

**Comment by souljungkim** [comment]
plz check #15

**Comment by souljungkim** [comment]
I think it's cool. 

However, if the middle part of the search word is corrected, the input cursor may not be natural.

That's because of this part. 
- https://github.com/JinseobBae/spread-sheet-project/pull/15/files#diff-3fcefcbd0ad57a61934666b26a93a3a671730fdc3001280b75d2a2d2d1f03906R19
    ```js
    window.getSelection().collapseToEnd();
    ```

I think that most of the search terms will be typed at once.

but, If needed later, I can try more.

**Comment by JinseobBae** [comment]
Thx!! 
This function has been merged to main
