### ISSUE TITLE
Take away internal information in code

### ISSUE THREAD

**Issue by JinseobBae** [JinseobBae/spread-sheet-project#17]
Some internal information typed in 'package-lock.json'

It's unnecessary info. 

Need to erase

**Comment by souljungkim** [comment]
@JinseobBae 

1. Check your registry 
    ```bash
    npm config get registry
    ```

2.  Modify the registry URL to the original server
    ```bash
    npm config set registry https://registry.npmjs.org/
    ```

3. Delete your package-lock.json
    ```bash
    rm package-lock.json
    ```

4. npm install again
    ```bash
    npm install
    ```
5. update your package-lock.json to git
    ```bash
    git add package-lock.json
    git commit -m 'blah blah'
    git push
    ```

**Comment by JinseobBae** [comment]
@souljungkim thx!!
