### ISSUE TITLE
Initialize Front-End

### ISSUE THREAD

**Issue by JinseobBae** [JinseobBae/spread-sheet-project#2]
Initialize Front-End (Vue.js)

**Comment by JinseobBae** [comment]
Use Vue.js 2, not 3!
Vue2 has more docs now

**Comment by souljungkim** [comment]
In my opinion, it is necessary to remove the '`package-lock.json`' file in which the `internal network IP is entered`.

**Comment by JinseobBae** [comment]
> In my opinion, it is necessary to remove the '`package-lock.json`' file in which the `internal network IP is entered`.

Good point. It doesn't need to contains internal info as you commented
I'm going to create issue for that
