### ISSUE TITLE
Context menu to add or delete row

### ISSUE THREAD

**Issue by JinseobBae** [JinseobBae/spread-sheet-project#23]
Now, use right click(add row) and  shift + right click(delete row)

add function context menu to add or delete row

**Comment by souljungkim** [comment]
Hello master  @JinseobBae 

https://github.com/JinseobBae/spread-sheet-project/pull/24 
I tested this project by applying 'menuman', one of the Context-Menu components that exist around the world.

❓ |  ✈
--------|-----
Source | https://github.com/sj-js/menuman
Document | https://sj-js.github.io/sj-js/menuman/

As a project leader, you need to find and select the optimal Context-Menu.

Good luck.

The documentation is not up-to-date and will be updated soon. 

Even so, the applied source is probably intuitively interpretable.
